// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SearchExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SearchExtensionString = "3615658b-2a49-4ad4-ad33-4b751a93d35e";
        public static Guid SearchExtension = new Guid(SearchExtensionString);

        public const string guidSearchExtensionPackageCmdSetString = "9fe7d6b8-faec-4f03-9598-0106f2108e90";
        public static Guid guidSearchExtensionPackageCmdSet = new Guid(guidSearchExtensionPackageCmdSetString);

        public const string guidImagesString = "f05fb9db-0eec-4ad6-8603-13551f43a874";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidSearchCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}